# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  # app service for backend
  app:
    container_name: youapp-backend-test
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_URI: mongodb://database:27017/youapp # DATABASE_URI, example: mongodb://database:27017
      JWT_SECRET: "nuyigybgtn546543%$#%$#"
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: # DATABASE_NAME
      # MONGO_INITDB_ROOT_PASSWORD: # DATABASE_USER